### ISSUE TITLE
No XE8 compatible

### ISSUE THREAD

**Issue by OceaBen** [yktoo/dklang#14]
Is there any chance to have a XE8 compatible version?
Specifically for 32&64 iOS….

Thanks !

**Comment by bjmillerpa** [comment]
New packages are now posted.

Bruce J. Miller
1-814-725-2312 voice
1-814-206-0362 fax

**Comment by OceaBen** [comment]
Thanks.

When I load the dklang220.bpl I can only build for Win32 and iOS64 (not iOS32 and Android)....

**Comment by OceaBen** [comment]
Hi,

So is there anyway to use this component under XE8 for Android, iOS32 and 64?

Thanks!

**Comment by bjmillerpa** [comment]
You only need to build it for Win32. Did you install dcldklang220.dpk, so
that you get the DKLang components in your component palette?

I just installed XE8 and tested DKLang. All worked without a problem.

Bruce J. Miller
1-814-725-2312 voice
1-814-206-0362 fax
