### ISSUE TITLE
FMX, XE8, First form opens second one, second form is not translated

### ISSUE THREAD

**Issue by dvpublic** [yktoo/dklang#17]
There is follow problem in fmx project under XE8.

There are two forms in the project. 
First form contains DKLTranslationsStorage instance. 
First form creates second form and opens it. 
Second form is not translated.

It looks like the problem is in DKLang.pas, line 1202. 
It's necessary to add follow code there:

`Stream.Seek(0, TSeekOrigin.soBeginning);`

then problem disappear.

**Comment by bjmillerpa** [comment]
Code updated. Please try latest commit.

**Comment by dvpublic** [comment]
Last commit works fine. Thanks a lot )
