### ISSUE TITLE
Translation missing on design elments like TSpeedbutton, TLabel, etc.

### ISSUE THREAD

**Issue by Athris** [yktoo/dklang#21]
Hello!

I use the version 4 of your DKLang component for Delphi XE2. I put on every form the DKLanguageControlle and name it "DKLanguageController". Every element caption or text is written in english. So i use your Translation Manager and create a new "German.lang" file.
![grafik](https://user-images.githubusercontent.com/11237138/33546376-1df65dfe-d8e1-11e7-9712-5fa46b9f738f.png)

I start my program and switch to german language. The main form changes and every element is in german, but now i open a other form by ShowModal(). The elements are not translated, but the used constraints (for grid title and messages) works.
![grafik](https://user-images.githubusercontent.com/11237138/33546683-f5522dc8-d8e1-11e7-8f30-f823683b6430.png)

In some ShowModal() dialogs does the translation work and other dialogs doesnt work. I dont know why.

I call the dialogs by follow code:
begin
  pntCardRarity := TfrmCardRarityDialog.Create(Self, fDebug);
  try
    pntCardRarity.fpntDatabase := dbeDatabase;
    pntCardRarity.ShowModal;
  finally
    pntCardRarity.Release;
end;

I try to recreated the whole DKLang and lang file, but that doesnt work. The DKLang file:
![grafik](https://user-images.githubusercontent.com/11237138/33546826-5c40d746-d8e2-11e7-9e1d-29e463862cd3.png)

The German.lang:
![grafik](https://user-images.githubusercontent.com/11237138/33546801-4b459486-d8e2-11e7-9978-1e6340d1e1b6.png)

**Comment by bjmillerpa** [comment]
Please try with the most current sources. This sounds like an issue that was resolved a long time ago. We only support the most current version.

**Comment by Athris** [comment]
Is it compatible with Delphi XE2?

**Comment by bjmillerpa** [comment]
I believe it is compatible with Delphi 2009 forward, when UnicodeString was made the default string type.

**Comment by Athris** [comment]
I try to compile the runtime package but i think it isnt possible.

Delphi XE2 doesnt know functions like
-result.IndexOf  (DK_LanguageCodes)
-result.Substring (DK_LanguageCodes)
-ws.Chars[i] (DkLang.pas)

**Comment by bjmillerpa** [comment]
Upon looking back this was briefly an issue with v5 and FireMonkey. See issue #17 from 23 Oct 2015. It describes the simple fix. I was wrong about compatibility timing. v5 was introduced with XE5 to support FireMonkey. v4 should be compatible back to D2009.

**Comment by Athris** [comment]
I try to write the Stream.Seek on Line 1341 but nothing changes:
![grafik](https://user-images.githubusercontent.com/11237138/33561472-0c02ee0a-d913-11e7-81ea-4980948366cc.png)

**Comment by Athris** [comment]
Okay. If i remove the unit from my project group it works. If i add the file again to the project group it doesnt work...

**Comment by bjmillerpa** [comment]
Are you saying that it works if you remove DKLang.pas from your project?

**Comment by bjmillerpa** [comment]
And by work, did you mean it compiles or translations work as expected.

**Comment by Athris** [comment]
Sorry i describe it clearly:
I have my main.pas and my subform.pas in my project manager. My main.pas looks like this:
```
unit main;

interface

uses
[other files], subform;

type
  TfrmMain = class(TForm)
[...]

implementation

procedure TfrmMain.mniStartsubFormClick(Sender: TObject);
var
  pntSubform: TfrmSubForm;
begin
  pntSubform:= TfrmSubForm.Create(Self);
  try
    pntSubform.ShowModal;
  finally
    pntSubform.Release;
  end;
end;
```

The subform.pas has only two buttons. The subform is in the main form uses area and the project manager. If i start my application the main form is correctly translate, but the subform isnt translate. 

Now if i remove the subform.pas from the project manager (only from project manager, not from the uses), then after successful compile my main form and my subform is correctly translate.

![grafik](https://user-images.githubusercontent.com/11237138/33624733-997e03d6-d9f5-11e7-824b-3fea89a8a32d.png)

If i add the subform.pas again to the project manager, the translation doesnt work.

**Comment by Athris** [comment]
Iam so stupid... its not the loaded problem. The project source code is already calling the subform:
```
begin
  Application.Initialize;
  Application.ShowMainForm := False;
  Application.MainFormOnTaskbar := False;
  Application.CreateForm(TfrmMain, frmMain);
  Application.CreateForm(TfrmSubform, frmSubform);
  Application.Run;
```

So on application startup, it loads the default language and dont translate the subform. Later if i show the subform, it doesnt translate again.

If i remove "Application.CreateForm(TfrmSubform, frmSubform);" it works. Sorry for the circumstances and thank your for your time!
