### ISSUE TITLE
Burmese Language Code

### ISSUE THREAD

**Issue by LingamYoni** [yktoo/dklang#26]
Please can you add Burmese Language Code? 
LCID Decimal = 1109
LCID Hexadecimal = 0x0455
For some reason, this language is not in the list for choosing languages:
![2019-11-12_154921](https://user-images.githubusercontent.com/40486018/68673336-8a193e00-0564-11ea-9bb2-c0d779558328.png)

**Comment by bjmillerpa** [comment]
I will look into it, but I am pretty sure it will require a re-compile of
the translation editor. I do not have access to current versions of all of
its components anymore so it might not happen.

**Comment by LingamYoni** [comment]
It's odd, but the Burmese language is missing in Windows 7, but if you run the translation editor in Windows 10, it appears in the list of available languages. 
Moreover, in the first case, the list of languages is sorted by Hexadecimal LCID, and in the second, it is unsorted at all.

**Comment by yktoo** [comment]
That's right. As far as I remember, the application simply lists the available languages provided by the system. So feel free to file a bug with Windows :)

**Comment by LingamYoni** [comment]
It's Weird Windows :)
