### ISSUE TITLE
How can I translate dynamic text

### ISSUE THREAD

**Issue by zystudios** [yktoo/dklang#30]
For example, how do I translate the text  in the following code, they are not static and not use in  xxx.Caption

```
// translate "this is number"
result := format('this is number %d',[number]);
```

```
var
s:string;
begin
// translate "This is number"   "please check it"
s := 'This is number' + inttostr(num) + 'please check it';
````

````
// translate "this is message"
showmessage("this is message");
````

I didn't find any examples in the demo, thanks!

**Comment by bjmillerpa** [comment]
Use constants. They allow you to define translated strings that are not
stored in components. They are defined in the Constants Editor available
from the "Project" menu under "DKLang - Edit Project Constants...'. There
are functions to access them from code:

   // Shortcut to LangManager.ConstantValueW[]
>   function  DKLangConstW(const wsName: UnicodeString): UnicodeString;
> overload;
>    // The same, but formats constant value using aParams
>   function  DKLangConstW(const wsName: UnicodeString; const aParams: Array
> of const): UnicodeString; overload;
>

*Bruce J. Miller*

*1-814-725-2312*

**Comment by zystudios** [comment]
Thanks
Example\Constants_VCL
